# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 667791b3fea3012fd99f93bfb1850e3d79884fa877e6b728e61f04307c4e99b6d6f5089f76bef159cedf9c142bd182c81bf5886a88f5ab2aaf3d840bc6531300

test:
  secret_key_base: 7d83b3eb72de84c7e75bed79f7bcf01586c7b553d4fc89244577bac1a4d2026faf6a601c0562105e4a8333367db692d411e06644bf9f9dc14292d7c14ae23aa8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
